language: ruby
#rvm:
# - 2.3.1


# apt addons:
#   # Optional
#

# cache components:
#   # Optional
#

bundler_args: ""--without development --retry 3"

before_install:
  - df -h
  - travis_retry gem update --system
  - travis_retry gem --version
  - travis_retry gem install bundler

install:
  - travis_retry bundle install

# before_script:
#

# script:
#

# before_cache:
#   # Optional
#

after_success:
  - declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/hydejack_pro_customers)"
  - openssl aes-256-cbc \
    -K $encrypted_fe89f28dd2a4_key
    -iv $encrypted_fe89f28dd2a4_iv \
    -in hydejack_pro_customers.enc \
    -out "$SSH_FILE" -d
  - chmod 600 "$SSH_FILE" \
    && printf "%s\n" \
      "Host hydejack" \
      "  HostName github.com" \
      "  IdentitiesOnly yes" \
      "  IdentityFile $SSH_FILE" \
      "  LogLevel ERROR" >> ~/.ssh/config

# after_failure:
#

# before_deploy:
#   # Optional
#

deploy:
  # Optional
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

# after_deploy:
#   # Optional
#

# after_script:
#
