language: ruby
#rvm:
# - 2.3.1


# apt addons:
#   # Optional
#

# cache components:
#   # Optional
#

bundler_args: "--without development --retry 3"

before_install:
  - df -h
  - travis_retry gem update --system
  - travis_retry gem --version
  - travis_retry gem install bundler

install:
  - travis_retry bundle install
  - ./.build/setup-hydejack.sh

# before_script:
#

# script:
#

# before_cache:
#   # Optional
#

# after_success:
#

# after_failure:
#

# before_deploy:
#   # Optional
#

deploy:
  # Optional
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

# after_deploy:
#   # Optional
#

# after_script:
#
